server:
  port: 8089

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    eureka-server-port: 8761
    healthcheck:
      enabled: true

spring:
  application:
    name: api-gateway-service
  config:
    import: "optional:configserver:"
  cloud:
    gateway:
      routes:
        - id: item-service
          uri: lb://ITEM-SERVICE
          predicates:
            - Path=/item-api/**
          filters:
            - RewritePath=/item-api/?(?<segment>.*), /$\{segment}
        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/order-api/**
          filters:
            - RewritePath=/order-api/?(?<segment>.*), /$\{segment}
        - id: account-service
          uri: lb://ACCOUNT-SERVICE
          predicates:
            - Path=/account-api/**
          filters:
            - RewritePath=/account-api/?(?<segment>.*), /$\{segment}